language: node_js

node_js:
  - '5'

install: npm install
script: npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: danieldelosreyesleal.com
  region: eu-west-3
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  cache_control: max-age=0
  
  
  
  