sudo: required
services:
  - docker

script:
  - docker build -t dandelea/portfolio
  - sh ./deploy.sh

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "danieldelosreyesleal.com"
  on:
    branch: master
  skip_cleanup: true
  region: eu-west-3