sudo: required

script:
  - npm install
  - npm run build
after_success:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws s3 sync ./dist s3://danieldelosreyesleal.com/