
name: Deployment

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploying application to GitHub pages
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'dandelea'
          reponame: 'portfolio'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
